version: "3.9"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn config.wsgi:application -b :8000"
    volumes:
      - web-static:/code/staticfiles
      - web-media:/code/mediafiles
    env_file:
      - ./envs/.env.dev
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./envs/.env.db.dev

  nginx:
    build: ./nginx
    volumes:
      - web-static:/code/staticfiles
      - web-media:/code/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  web-static:
  web-media:
  pgdata:
