version: "3.9"

services:
  dev-web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./envs/.env.dev
    ports:
      - 8000:8000
    depends_on:
      - dev-db

  dev-db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./envs/.env.db.dev

volumes:
  pgdata:
