version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application -b :8000"
    volumes:
      - web-static:/code/static
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
    - pgdata:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    volumes:
      - web-static:/code/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  web-static:
  pgdata: