# Generated by Django 3.1.8 on 2021-06-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210612_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='year_of_admission',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='students',
            field=models.ManyToManyField(related_name='student_groups', to='accounts.StudentProfile'),
        ),
    ]
