# Generated by Django 3.1.7 on 2021-04-07 08:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_instructorprofile_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('syllabus', models.TextField(blank=True)),
                ('instructors', models.ManyToManyField(related_name='instructors', to='accounts.InstructorProfile')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(verbose_name='Course start date')),
                ('end_date', models.DateField(verbose_name='Course end date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='lms_core.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('students', models.ManyToManyField(to='accounts.StudentProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(verbose_name='Event start time')),
                ('end_time', models.TimeField(verbose_name='Event end time')),
                ('weekday', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', max_length=2)),
                ('repeat_type', models.CharField(choices=[('W', 'Weekly'), ('E', 'Even'), ('O', 'Odd')], default='W', max_length=1)),
                ('event_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lms_core.eventtype')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.instructorprofile')),
                ('students', models.ManyToManyField(to='accounts.StudentProfile')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.timetable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonPeriodicEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(verbose_name='Event start time')),
                ('end_time', models.TimeField(verbose_name='Event end time')),
                ('date', models.DateField()),
                ('event_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lms_core.eventtype')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.instructorprofile')),
                ('students', models.ManyToManyField(to='accounts.StudentProfile')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.timetable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='student_groups',
            field=models.ManyToManyField(to='lms_core.StudentGroup'),
        ),
    ]
