# Generated by Django 3.1.7 on 2021-04-13 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonperiodicevent',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.eventtype'),
        ),
        migrations.AlterField(
            model_name='periodicevent',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.eventtype'),
        ),
    ]
