# Generated by Django 3.2 on 2021-04-29 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms_core', '0004_auto_20210429_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='request',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.AlterField(
            model_name='request',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('status', models.CharField(choices=[('P', 'InProcessing'), ('A', 'Approved'), ('D', 'Declined')], default='P', max_length=1)),
                ('comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lms_core.request')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
