# Generated by Django 3.1.8 on 2021-05-05 16:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210430_0857'),
        ('lms_core', '0006_auto_20210430_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.eventtype')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.timetable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonPeriodicEventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('start_time', models.TimeField(verbose_name='Event start time')),
                ('end_time', models.TimeField(verbose_name='Event end time')),
                ('date', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.event')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.instructorprofile')),
                ('students', models.ManyToManyField(to='accounts.StudentProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodicEventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('start_time', models.TimeField(verbose_name='Event start time')),
                ('end_time', models.TimeField(verbose_name='Event end time')),
                ('weekday', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', max_length=2)),
                ('repeat_type', models.CharField(choices=[('W', 'Weekly'), ('E', 'Even'), ('O', 'Odd')], default='W', max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.event')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.instructorprofile')),
                ('students', models.ManyToManyField(to='accounts.StudentProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='periodicevent',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='periodicevent',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='periodicevent',
            name='students',
        ),
        migrations.RemoveField(
            model_name='periodicevent',
            name='timetable',
        ),
        migrations.DeleteModel(
            name='NonPeriodicEvent',
        ),
        migrations.DeleteModel(
            name='PeriodicEvent',
        ),
    ]
