# Generated by Django 3.1.8 on 2021-05-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210430_0857'),
        ('lms_core', '0007_auto_20210505_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='instructed_courses', to='accounts.InstructorProfile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_groups',
            field=models.ManyToManyField(related_name='joined_courses', to='lms_core.StudentGroup'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='students',
            field=models.ManyToManyField(related_name='groups', to='accounts.StudentProfile'),
        ),
    ]
