# Generated by Django 3.1.8 on 2021-05-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_studentgroup'),
        ('education', '0002_auto_20210517_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='accounts.instructorprofile'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='students',
            field=models.ManyToManyField(related_name='assignment', to='accounts.StudentProfile'),
        ),
    ]
