# Generated by Django 3.1.8 on 2021-05-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_assignmentcontent_coursecontent_solutioncontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
