# Generated by Django 3.1.8 on 2021-05-21 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_studentgroup'),
        ('education', '0005_grade_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='accounts.instructorprofile'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='students',
            field=models.ManyToManyField(related_name='assignments', to='accounts.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='education.timetable'),
        ),
    ]
