# Generated by Django 3.1.8 on 2021-05-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_auto_20210521_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='solution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='education.solution'),
        ),
    ]
