# Generated by Django 3.1.8 on 2021-06-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20210522_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='education.timetable'),
        ),
    ]
